source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AutoAutoLayout_Example', :exclusive => true do
  pod "AutoAutoLayout", :path => "../"
end

target 'AutoAutoLayout_Tests', :exclusive => true do
  pod "AutoAutoLayout", :path => "../"

  
end
